# Generated by Django 4.1.2 on 2022-12-04 04:20

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('booking_status', models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], default='Booked', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('final_cost', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=20)),
                ('routing_number', models.CharField(max_length=9)),
                ('account_number', models.CharField(max_length=20)),
                ('card_expiry', models.DateField()),
                ('billing_address', models.CharField(blank=True, max_length=256)),
                ('account_name', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('plate_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vehicle_make', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(max_length=20)),
                ('built_year', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('vehicle_class', models.CharField(max_length=20)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
